version: '3.8'

services:
  ############################################
  # cAdvisor - Collect Docker container metrics
  ############################################
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  ############################################
  # Prometheus - Scrape metrics (cAdvisor, itself)
  ############################################
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  ############################################
  # Loki - Store and query logs
  ############################################
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    command: [ '-config.file=/etc/loki/local-config.yaml' ]
    restart: unless-stopped

  ############################################
  # Promtail - Collect Docker logs & push to Loki
  ############################################
  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    command: 
      - "--config.file=/etc/promtail/promtail-config.yml"
    restart: unless-stopped

  ############################################
  # Grafana - Visualization for metrics & logs
  ############################################
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data: